### ISSUE TITLE
Moan.UI.boxColour doesn't seem to work

### ISSUE THREAD

**Issue by elennick** [ttxi/Moan.lua#5]
I spent a while trying to get the `Moan.UI.boxColour` configuration option working and was not able to get it to affect the box color at all. Some examples of how i tried using it:

As part of a speak() config:
```    
Moan.speak({ "Test Person", { 255, 255, 255 } },
            { "test msg" },
            { image = portrait,
              onstart = function()
                  Moan.UI.boxColour = { 66, 244, 215  }
                  Moan.UI.messageboxPos = "bottom"
              end })
```

As part of an initial config setting:
```
Moan.UI.boxColour = { 66, 244, 215 }
Moan.speak({ "Test Person", { 255, 255, 255 } }, { "test msg" }, { image = portrait })
```

Eventually I just went into the library itself and modified `local boxColour` and that worked but obviously I'd rather configure within my code then modify the library in a hacky fashion like that. Can you let me know if this is a legit issue or if I'm just doing something wrong?

**Comment by flamendless** [comment]
What version of löve do you use?

**Comment by elennick** [comment]
@flamendless  11.1.0

**Comment by flamendless** [comment]
Löve 11+ uses color range of 0.0 to 1.0

**Comment by elennick** [comment]
I just had the same realization a few minutes ago... thanks @flamendless. Says it changed as of 11.x: https://love2d.org/wiki/love.graphics.setColor

```
In versions prior to 11.0, color component values were within the range of 0 to 255 instead of 0 to 1. 
```

I'll leave this open since it is still relevant... looks like Moan still uses 0 to 255 in its code.

**Comment by ttxi** [comment]
#6 fixes this.
